// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/v1/identity.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentityType int32

const (
	IdentityType_IDENTITY_TYPE_UNSPECIFIED IdentityType = 0
	IdentityType_IDENTITY_TYPE_USER        IdentityType = 1
	IdentityType_IDENTITY_TYPE_SYSTEM      IdentityType = 2
)

// Enum value maps for IdentityType.
var (
	IdentityType_name = map[int32]string{
		0: "IDENTITY_TYPE_UNSPECIFIED",
		1: "IDENTITY_TYPE_USER",
		2: "IDENTITY_TYPE_SYSTEM",
	}
	IdentityType_value = map[string]int32{
		"IDENTITY_TYPE_UNSPECIFIED": 0,
		"IDENTITY_TYPE_USER":        1,
		"IDENTITY_TYPE_SYSTEM":      2,
	}
)

func (x IdentityType) Enum() *IdentityType {
	p := new(IdentityType)
	*p = x
	return p
}

func (x IdentityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentityType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_identity_proto_enumTypes[0].Descriptor()
}

func (IdentityType) Type() protoreflect.EnumType {
	return &file_common_v1_identity_proto_enumTypes[0]
}

func (x IdentityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdentityType.Descriptor instead.
func (IdentityType) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_identity_proto_rawDescGZIP(), []int{0}
}

type Identity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates the type of the creator (User or System)
	Type IdentityType `protobuf:"varint,1,opt,name=type,proto3,enum=common.v1.IdentityType" json:"type,omitempty"`
	// Contains details of the creator, either user or system
	//
	// Types that are valid to be assigned to Details:
	//
	//	*Identity_User
	//	*Identity_System
	Details       isIdentity_Details `protobuf_oneof:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_common_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_common_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *Identity) GetType() IdentityType {
	if x != nil {
		return x.Type
	}
	return IdentityType_IDENTITY_TYPE_UNSPECIFIED
}

func (x *Identity) GetDetails() isIdentity_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Identity) GetUser() *UserActor {
	if x != nil {
		if x, ok := x.Details.(*Identity_User); ok {
			return x.User
		}
	}
	return nil
}

func (x *Identity) GetSystem() *SystemActor {
	if x != nil {
		if x, ok := x.Details.(*Identity_System); ok {
			return x.System
		}
	}
	return nil
}

type isIdentity_Details interface {
	isIdentity_Details()
}

type Identity_User struct {
	User *UserActor `protobuf:"bytes,2,opt,name=user,proto3,oneof"`
}

type Identity_System struct {
	System *SystemActor `protobuf:"bytes,3,opt,name=system,proto3,oneof"`
}

func (*Identity_User) isIdentity_Details() {}

func (*Identity_System) isIdentity_Details() {}

type UserActor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Spiffe/Spite workload identity or global management system id
	UserId           string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserLdap         string `protobuf:"bytes,2,opt,name=user_ldap,json=userLdap,proto3" json:"user_ldap,omitempty"`
	IsServiceAccount bool   `protobuf:"varint,3,opt,name=is_service_account,json=isServiceAccount,proto3" json:"is_service_account,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserActor) Reset() {
	*x = UserActor{}
	mi := &file_common_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserActor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserActor) ProtoMessage() {}

func (x *UserActor) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserActor.ProtoReflect.Descriptor instead.
func (*UserActor) Descriptor() ([]byte, []int) {
	return file_common_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *UserActor) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserActor) GetUserLdap() string {
	if x != nil {
		return x.UserLdap
	}
	return ""
}

func (x *UserActor) GetIsServiceAccount() bool {
	if x != nil {
		return x.IsServiceAccount
	}
	return false
}

// =========================
// System Creator
// =========================
type SystemActor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Spiffe/Spite workload identity or global management system id
	SystemId          string     `protobuf:"bytes,1,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	SystemName        string     `protobuf:"bytes,2,opt,name=system_name,json=systemName,proto3" json:"system_name,omitempty"`
	SystemEnvironment string     `protobuf:"bytes,3,opt,name=system_environment,json=systemEnvironment,proto3" json:"system_environment,omitempty"`
	FederatedUser     *UserActor `protobuf:"bytes,4,opt,name=federated_user,json=federatedUser,proto3,oneof" json:"federated_user,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SystemActor) Reset() {
	*x = SystemActor{}
	mi := &file_common_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemActor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemActor) ProtoMessage() {}

func (x *SystemActor) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemActor.ProtoReflect.Descriptor instead.
func (*SystemActor) Descriptor() ([]byte, []int) {
	return file_common_v1_identity_proto_rawDescGZIP(), []int{2}
}

func (x *SystemActor) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *SystemActor) GetSystemName() string {
	if x != nil {
		return x.SystemName
	}
	return ""
}

func (x *SystemActor) GetSystemEnvironment() string {
	if x != nil {
		return x.SystemEnvironment
	}
	return ""
}

func (x *SystemActor) GetFederatedUser() *UserActor {
	if x != nil {
		return x.FederatedUser
	}
	return nil
}

var File_common_v1_identity_proto protoreflect.FileDescriptor

const file_common_v1_identity_proto_rawDesc = "" +
	"\n" +
	"\x18common/v1/identity.proto\x12\tcommon.v1\"\xa0\x01\n" +
	"\bIdentity\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.common.v1.IdentityTypeR\x04type\x12*\n" +
	"\x04user\x18\x02 \x01(\v2\x14.common.v1.UserActorH\x00R\x04user\x120\n" +
	"\x06system\x18\x03 \x01(\v2\x16.common.v1.SystemActorH\x00R\x06systemB\t\n" +
	"\adetails\"o\n" +
	"\tUserActor\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_ldap\x18\x02 \x01(\tR\buserLdap\x12,\n" +
	"\x12is_service_account\x18\x03 \x01(\bR\x10isServiceAccount\"\xcf\x01\n" +
	"\vSystemActor\x12\x1b\n" +
	"\tsystem_id\x18\x01 \x01(\tR\bsystemId\x12\x1f\n" +
	"\vsystem_name\x18\x02 \x01(\tR\n" +
	"systemName\x12-\n" +
	"\x12system_environment\x18\x03 \x01(\tR\x11systemEnvironment\x12@\n" +
	"\x0efederated_user\x18\x04 \x01(\v2\x14.common.v1.UserActorH\x00R\rfederatedUser\x88\x01\x01B\x11\n" +
	"\x0f_federated_user*_\n" +
	"\fIdentityType\x12\x1d\n" +
	"\x19IDENTITY_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12IDENTITY_TYPE_USER\x10\x01\x12\x18\n" +
	"\x14IDENTITY_TYPE_SYSTEM\x10\x02B\x9a\x01\n" +
	"\rcom.common.v1B\rIdentityProtoH\x02P\x01Z3github.com/copito/runner/idl_gen/common/v1;commonv1\xa2\x02\x03CXX\xaa\x02\tCommon.V1\xca\x02\tCommon\\V1\xe2\x02\x15Common\\V1\\GPBMetadata\xea\x02\n" +
	"Common::V1b\x06proto3"

var (
	file_common_v1_identity_proto_rawDescOnce sync.Once
	file_common_v1_identity_proto_rawDescData []byte
)

func file_common_v1_identity_proto_rawDescGZIP() []byte {
	file_common_v1_identity_proto_rawDescOnce.Do(func() {
		file_common_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_identity_proto_rawDesc), len(file_common_v1_identity_proto_rawDesc)))
	})
	return file_common_v1_identity_proto_rawDescData
}

var file_common_v1_identity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_v1_identity_proto_goTypes = []any{
	(IdentityType)(0),   // 0: common.v1.IdentityType
	(*Identity)(nil),    // 1: common.v1.Identity
	(*UserActor)(nil),   // 2: common.v1.UserActor
	(*SystemActor)(nil), // 3: common.v1.SystemActor
}
var file_common_v1_identity_proto_depIdxs = []int32{
	0, // 0: common.v1.Identity.type:type_name -> common.v1.IdentityType
	2, // 1: common.v1.Identity.user:type_name -> common.v1.UserActor
	3, // 2: common.v1.Identity.system:type_name -> common.v1.SystemActor
	2, // 3: common.v1.SystemActor.federated_user:type_name -> common.v1.UserActor
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_common_v1_identity_proto_init() }
func file_common_v1_identity_proto_init() {
	if File_common_v1_identity_proto != nil {
		return
	}
	file_common_v1_identity_proto_msgTypes[0].OneofWrappers = []any{
		(*Identity_User)(nil),
		(*Identity_System)(nil),
	}
	file_common_v1_identity_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_identity_proto_rawDesc), len(file_common_v1_identity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_identity_proto_goTypes,
		DependencyIndexes: file_common_v1_identity_proto_depIdxs,
		EnumInfos:         file_common_v1_identity_proto_enumTypes,
		MessageInfos:      file_common_v1_identity_proto_msgTypes,
	}.Build()
	File_common_v1_identity_proto = out.File
	file_common_v1_identity_proto_goTypes = nil
	file_common_v1_identity_proto_depIdxs = nil
}
