// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID        uuid.UUID
	UserID    pgtype.UUID
	Amount    pgtype.Numeric
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID        uuid.UUID
	Username  string
	Email     string
	Tenancy   string
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}
