// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runner.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    email,
    tenancy
) VALUES (
    $1::text,
    $2::text,
    $3::text
) RETURNING id, username, email, tenancy, created_at, deleted_at
`

type CreateUserParams struct {
	Username string
	Email    string
	Tenancy  pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (User, error) {
	row := db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.Tenancy)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Tenancy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET
    deleted_at = NOW()
WHERE id = $1::uuid
`

func (q *Queries) DeleteUser(ctx context.Context, db DBTX, id uuid.UUID) error {
	_, err := db.Exec(ctx, deleteUser, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, username, email, tenancy, created_at, deleted_at FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context, db DBTX) ([]User, error) {
	rows, err := db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Tenancy,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, tenancy, created_at, deleted_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, db DBTX, id uuid.UUID) (User, error) {
	row := db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Tenancy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, email, tenancy, created_at, deleted_at FROM users
WHERE 1=1
AND tenancy = $1::text
AND ($2::text[] IS NULL OR username = ANY($2::text[]))
AND ($3::text[] IS NULL OR email = ANY($3::text[]))
ORDER BY created_at DESC
LIMIT $5::int
OFFSET $4::int
`

type SearchUsersParams struct {
	Tenancy         string
	UsernameFilters []string
	EmailFilters    []string
	OffsetVal       int32
	LimitVal        int32
}

func (q *Queries) SearchUsers(ctx context.Context, db DBTX, arg SearchUsersParams) ([]User, error) {
	rows, err := db.Query(ctx, searchUsers,
		arg.Tenancy,
		arg.UsernameFilters,
		arg.EmailFilters,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Tenancy,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
