image:
  repository: docker.example.com/platform/prof
  tag: latest

tags:
  consumer: testing
  owner: copito
  application: prof

http:
  containerPort: 5005
  healthcheck:
    port: 5005
  grpcOnly: false
  grpc:
    containerPort: 50051
    healthcheck:
      path: /grpc.health.v1.Health/Check
