// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: runner/v1/query.proto

package runnerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RunnerService_Ping_FullMethodName                = "/runner.v1.RunnerService/Ping"
	RunnerService_GetAvailableEngines_FullMethodName = "/runner.v1.RunnerService/GetAvailableEngines"
	RunnerService_SubmitQuery_FullMethodName         = "/runner.v1.RunnerService/SubmitQuery"
	RunnerService_SubmitQueryAsync_FullMethodName    = "/runner.v1.RunnerService/SubmitQueryAsync"
	RunnerService_CheckQueryStatus_FullMethodName    = "/runner.v1.RunnerService/CheckQueryStatus"
	RunnerService_GetQueryResult_FullMethodName      = "/runner.v1.RunnerService/GetQueryResult"
)

// RunnerServiceClient is the client API for RunnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RunnerServiceClient interface {
	// Testing function for Runner Service
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Get available query engines
	GetAvailableEngines(ctx context.Context, in *GetAvailableEnginesRequest, opts ...grpc.CallOption) (*GetAvailableEnginesResponse, error)
	// Submit query to the service synchonously
	SubmitQuery(ctx context.Context, in *SubmitQueryRequest, opts ...grpc.CallOption) (*QueryResultResponse, error)
	// Submit query to the service asynchonously
	SubmitQueryAsync(ctx context.Context, in *SubmitQueryRequest, opts ...grpc.CallOption) (*SubmitQueryAsyncResponse, error)
	// Check the query status submitted (or done)
	CheckQueryStatus(ctx context.Context, in *CheckQueryStatusRequest, opts ...grpc.CallOption) (*CheckQueryStatusResponse, error)
	// Gets query result if query has been completed
	GetQueryResult(ctx context.Context, in *GetQueryResultRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResultResponse], error)
}

type runnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnerServiceClient(cc grpc.ClientConnInterface) RunnerServiceClient {
	return &runnerServiceClient{cc}
}

func (c *runnerServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, RunnerService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) GetAvailableEngines(ctx context.Context, in *GetAvailableEnginesRequest, opts ...grpc.CallOption) (*GetAvailableEnginesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailableEnginesResponse)
	err := c.cc.Invoke(ctx, RunnerService_GetAvailableEngines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) SubmitQuery(ctx context.Context, in *SubmitQueryRequest, opts ...grpc.CallOption) (*QueryResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResultResponse)
	err := c.cc.Invoke(ctx, RunnerService_SubmitQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) SubmitQueryAsync(ctx context.Context, in *SubmitQueryRequest, opts ...grpc.CallOption) (*SubmitQueryAsyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitQueryAsyncResponse)
	err := c.cc.Invoke(ctx, RunnerService_SubmitQueryAsync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) CheckQueryStatus(ctx context.Context, in *CheckQueryStatusRequest, opts ...grpc.CallOption) (*CheckQueryStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckQueryStatusResponse)
	err := c.cc.Invoke(ctx, RunnerService_CheckQueryStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) GetQueryResult(ctx context.Context, in *GetQueryResultRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResultResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RunnerService_ServiceDesc.Streams[0], RunnerService_GetQueryResult_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetQueryResultRequest, QueryResultResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunnerService_GetQueryResultClient = grpc.ServerStreamingClient[QueryResultResponse]

// RunnerServiceServer is the server API for RunnerService service.
// All implementations must embed UnimplementedRunnerServiceServer
// for forward compatibility.
type RunnerServiceServer interface {
	// Testing function for Runner Service
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Get available query engines
	GetAvailableEngines(context.Context, *GetAvailableEnginesRequest) (*GetAvailableEnginesResponse, error)
	// Submit query to the service synchonously
	SubmitQuery(context.Context, *SubmitQueryRequest) (*QueryResultResponse, error)
	// Submit query to the service asynchonously
	SubmitQueryAsync(context.Context, *SubmitQueryRequest) (*SubmitQueryAsyncResponse, error)
	// Check the query status submitted (or done)
	CheckQueryStatus(context.Context, *CheckQueryStatusRequest) (*CheckQueryStatusResponse, error)
	// Gets query result if query has been completed
	GetQueryResult(*GetQueryResultRequest, grpc.ServerStreamingServer[QueryResultResponse]) error
	mustEmbedUnimplementedRunnerServiceServer()
}

// UnimplementedRunnerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunnerServiceServer struct{}

func (UnimplementedRunnerServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRunnerServiceServer) GetAvailableEngines(context.Context, *GetAvailableEnginesRequest) (*GetAvailableEnginesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailableEngines not implemented")
}
func (UnimplementedRunnerServiceServer) SubmitQuery(context.Context, *SubmitQueryRequest) (*QueryResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitQuery not implemented")
}
func (UnimplementedRunnerServiceServer) SubmitQueryAsync(context.Context, *SubmitQueryRequest) (*SubmitQueryAsyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitQueryAsync not implemented")
}
func (UnimplementedRunnerServiceServer) CheckQueryStatus(context.Context, *CheckQueryStatusRequest) (*CheckQueryStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckQueryStatus not implemented")
}
func (UnimplementedRunnerServiceServer) GetQueryResult(*GetQueryResultRequest, grpc.ServerStreamingServer[QueryResultResponse]) error {
	return status.Error(codes.Unimplemented, "method GetQueryResult not implemented")
}
func (UnimplementedRunnerServiceServer) mustEmbedUnimplementedRunnerServiceServer() {}
func (UnimplementedRunnerServiceServer) testEmbeddedByValue()                       {}

// UnsafeRunnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnerServiceServer will
// result in compilation errors.
type UnsafeRunnerServiceServer interface {
	mustEmbedUnimplementedRunnerServiceServer()
}

func RegisterRunnerServiceServer(s grpc.ServiceRegistrar, srv RunnerServiceServer) {
	// If the following call panics, it indicates UnimplementedRunnerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RunnerService_ServiceDesc, srv)
}

func _RunnerService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_GetAvailableEngines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableEnginesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).GetAvailableEngines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_GetAvailableEngines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).GetAvailableEngines(ctx, req.(*GetAvailableEnginesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_SubmitQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).SubmitQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_SubmitQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).SubmitQuery(ctx, req.(*SubmitQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_SubmitQueryAsync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).SubmitQueryAsync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_SubmitQueryAsync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).SubmitQueryAsync(ctx, req.(*SubmitQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_CheckQueryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckQueryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).CheckQueryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_CheckQueryStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).CheckQueryStatus(ctx, req.(*CheckQueryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_GetQueryResult_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetQueryResultRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RunnerServiceServer).GetQueryResult(m, &grpc.GenericServerStream[GetQueryResultRequest, QueryResultResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunnerService_GetQueryResultServer = grpc.ServerStreamingServer[QueryResultResponse]

// RunnerService_ServiceDesc is the grpc.ServiceDesc for RunnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runner.v1.RunnerService",
	HandlerType: (*RunnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _RunnerService_Ping_Handler,
		},
		{
			MethodName: "GetAvailableEngines",
			Handler:    _RunnerService_GetAvailableEngines_Handler,
		},
		{
			MethodName: "SubmitQuery",
			Handler:    _RunnerService_SubmitQuery_Handler,
		},
		{
			MethodName: "SubmitQueryAsync",
			Handler:    _RunnerService_SubmitQueryAsync_Handler,
		},
		{
			MethodName: "CheckQueryStatus",
			Handler:    _RunnerService_CheckQueryStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetQueryResult",
			Handler:       _RunnerService_GetQueryResult_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "runner/v1/query.proto",
}
