// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: runner/v1/query.proto

package runnerv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/copito/runner/idl_gen/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Job Status refers to the current state in which the job query is in
// This helps determine if the query has been send, received by the worker
// and the worker is ready to receive the results.
type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED     JobStatus = 0
	JobStatus_JOB_STATUS_SUBMITTED       JobStatus = 1
	JobStatus_JOB_STATUS_QUEUED          JobStatus = 2
	JobStatus_JOB_STATUS_WORKER_STARTED  JobStatus = 3
	JobStatus_JOB_STATUS_RUNNING         JobStatus = 4
	JobStatus_JOB_STATUS_FAILED          JobStatus = 5
	JobStatus_JOB_STATUS_SUCCESSFUL      JobStatus = 6
	JobStatus_JOB_STATUS_RETRIEVING_DATA JobStatus = 7
	JobStatus_JOB_STATUS_WORKER_STOPPED  JobStatus = 8
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_SUBMITTED",
		2: "JOB_STATUS_QUEUED",
		3: "JOB_STATUS_WORKER_STARTED",
		4: "JOB_STATUS_RUNNING",
		5: "JOB_STATUS_FAILED",
		6: "JOB_STATUS_SUCCESSFUL",
		7: "JOB_STATUS_RETRIEVING_DATA",
		8: "JOB_STATUS_WORKER_STOPPED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED":     0,
		"JOB_STATUS_SUBMITTED":       1,
		"JOB_STATUS_QUEUED":          2,
		"JOB_STATUS_WORKER_STARTED":  3,
		"JOB_STATUS_RUNNING":         4,
		"JOB_STATUS_FAILED":          5,
		"JOB_STATUS_SUCCESSFUL":      6,
		"JOB_STATUS_RETRIEVING_DATA": 7,
		"JOB_STATUS_WORKER_STOPPED":  8,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_runner_v1_query_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_runner_v1_query_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_runner_v1_query_proto_rawDescGZIP(), []int{0}
}

// Job Type defines what type of synchronicity does the job expect
// the results to be returned in (SYNC / ASYNC), where the async
// route should be the default to avoid tieing worker with client (due to scalability)
type JobType int32

const (
	JobType_JOB_TYPE_UNSPECIFIED JobType = 0
	JobType_JOB_TYPE_SYNC        JobType = 1
	JobType_JOB_TYPE_ASYNC       JobType = 2
)

// Enum value maps for JobType.
var (
	JobType_name = map[int32]string{
		0: "JOB_TYPE_UNSPECIFIED",
		1: "JOB_TYPE_SYNC",
		2: "JOB_TYPE_ASYNC",
	}
	JobType_value = map[string]int32{
		"JOB_TYPE_UNSPECIFIED": 0,
		"JOB_TYPE_SYNC":        1,
		"JOB_TYPE_ASYNC":       2,
	}
)

func (x JobType) Enum() *JobType {
	p := new(JobType)
	*p = x
	return p
}

func (x JobType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobType) Descriptor() protoreflect.EnumDescriptor {
	return file_runner_v1_query_proto_enumTypes[1].Descriptor()
}

func (JobType) Type() protoreflect.EnumType {
	return &file_runner_v1_query_proto_enumTypes[1]
}

func (x JobType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobType.Descriptor instead.
func (JobType) EnumDescriptor() ([]byte, []int) {
	return file_runner_v1_query_proto_rawDescGZIP(), []int{1}
}

// This is a list of key value pairs (dictionary) that will be passed to the query,
// so that the templating engine can add these to the query or modify the templated
// query before being run by query engine.
type QueryParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParams) Reset() {
	*x = QueryParams{}
	mi := &file_runner_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParams) ProtoMessage() {}

func (x *QueryParams) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParams.ProtoReflect.Descriptor instead.
func (*QueryParams) Descriptor() ([]byte, []int) {
	return file_runner_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryParams) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *QueryParams) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// This represents the metadata of a query result, which includes
// column names and data types. This is used to inform the client
// about the structure of the data they are receiving.
type QueryResultMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`                      // i.e. ["uuid", "price", "effective_date", "created_at"]
	DataTypes     []string               `protobuf:"bytes,2,rep,name=data_types,json=dataTypes,proto3" json:"data_types,omitempty"` // i.e. ["string", "float", "date", "timestamp"]
	RowCount      string                 `protobuf:"bytes,3,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`    // i.e. 500
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResultMetadata) Reset() {
	*x = QueryResultMetadata{}
	mi := &file_runner_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResultMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResultMetadata) ProtoMessage() {}

func (x *QueryResultMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResultMetadata.ProtoReflect.Descriptor instead.
func (*QueryResultMetadata) Descriptor() ([]byte, []int) {
	return file_runner_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResultMetadata) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *QueryResultMetadata) GetDataTypes() []string {
	if x != nil {
		return x.DataTypes
	}
	return nil
}

func (x *QueryResultMetadata) GetRowCount() string {
	if x != nil {
		return x.RowCount
	}
	return ""
}

// QueryJob represents
type QueryJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobUuid       string                 `protobuf:"bytes,1,opt,name=job_uuid,json=jobUuid,proto3" json:"job_uuid,omitempty"`
	Reference     string                 `protobuf:"bytes,2,opt,name=reference,proto3" json:"reference,omitempty"`
	Status        JobStatus              `protobuf:"varint,3,opt,name=status,proto3,enum=runner.v1.JobStatus" json:"status,omitempty"`
	JobType       JobType                `protobuf:"varint,4,opt,name=job_type,json=jobType,proto3,enum=runner.v1.JobType" json:"job_type,omitempty"` // i.e. SYNC
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	AdjustedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=adjusted_at,json=adjustedAt,proto3" json:"adjusted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryJob) Reset() {
	*x = QueryJob{}
	mi := &file_runner_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryJob) ProtoMessage() {}

func (x *QueryJob) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryJob.ProtoReflect.Descriptor instead.
func (*QueryJob) Descriptor() ([]byte, []int) {
	return file_runner_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryJob) GetJobUuid() string {
	if x != nil {
		return x.JobUuid
	}
	return ""
}

func (x *QueryJob) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *QueryJob) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *QueryJob) GetJobType() JobType {
	if x != nil {
		return x.JobType
	}
	return JobType_JOB_TYPE_UNSPECIFIED
}

func (x *QueryJob) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *QueryJob) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *QueryJob) GetAdjustedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AdjustedAt
	}
	return nil
}

// Ping Command
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_runner_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_runner_v1_query_proto_rawDescGZIP(), []int{3}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_runner_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_runner_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAvailableEnginesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableEnginesRequest) Reset() {
	*x = GetAvailableEnginesRequest{}
	mi := &file_runner_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableEnginesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableEnginesRequest) ProtoMessage() {}

func (x *GetAvailableEnginesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableEnginesRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableEnginesRequest) Descriptor() ([]byte, []int) {
	return file_runner_v1_query_proto_rawDescGZIP(), []int{5}
}

type GetAvailableEnginesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Engines       []string               `protobuf:"bytes,1,rep,name=engines,proto3" json:"engines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableEnginesResponse) Reset() {
	*x = GetAvailableEnginesResponse{}
	mi := &file_runner_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableEnginesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableEnginesResponse) ProtoMessage() {}

func (x *GetAvailableEnginesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableEnginesResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableEnginesResponse) Descriptor() ([]byte, []int) {
	return file_runner_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *GetAvailableEnginesResponse) GetEngines() []string {
	if x != nil {
		return x.Engines
	}
	return nil
}

type SubmitQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Engine        string                 `protobuf:"bytes,2,opt,name=engine,proto3" json:"engine,omitempty"`
	Params        []*QueryParams         `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	JobType       JobType                `protobuf:"varint,4,opt,name=job_type,json=jobType,proto3,enum=runner.v1.JobType" json:"job_type,omitempty"`
	Operator      v1.ComparisonOperator  `protobuf:"varint,5,opt,name=operator,proto3,enum=common.v1.ComparisonOperator" json:"operator,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitQueryRequest) Reset() {
	*x = SubmitQueryRequest{}
	mi := &file_runner_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitQueryRequest) ProtoMessage() {}

func (x *SubmitQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitQueryRequest.ProtoReflect.Descriptor instead.
func (*SubmitQueryRequest) Descriptor() ([]byte, []int) {
	return file_runner_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SubmitQueryRequest) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *SubmitQueryRequest) GetParams() []*QueryParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *SubmitQueryRequest) GetJobType() JobType {
	if x != nil {
		return x.JobType
	}
	return JobType_JOB_TYPE_UNSPECIFIED
}

func (x *SubmitQueryRequest) GetOperator() v1.ComparisonOperator {
	if x != nil {
		return x.Operator
	}
	return v1.ComparisonOperator(0)
}

func (x *SubmitQueryRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type QueryResultResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Job            *QueryJob              `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	Data           string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	JobType        JobType                `protobuf:"varint,3,opt,name=job_type,json=jobType,proto3,enum=runner.v1.JobType" json:"job_type,omitempty"`
	ResultMetadata *QueryResultMetadata   `protobuf:"bytes,4,opt,name=result_metadata,json=resultMetadata,proto3" json:"result_metadata,omitempty"` // i.e. {'columns': [], 'data_types': []}
	EngineMetadata *structpb.Struct       `protobuf:"bytes,5,opt,name=engine_metadata,json=engineMetadata,proto3" json:"engine_metadata,omitempty"` // i.e. {'execution_time_in_sec': 2.33, 'traceback': false, ...}
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryResultResponse) Reset() {
	*x = QueryResultResponse{}
	mi := &file_runner_v1_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResultResponse) ProtoMessage() {}

func (x *QueryResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResultResponse.ProtoReflect.Descriptor instead.
func (*QueryResultResponse) Descriptor() ([]byte, []int) {
	return file_runner_v1_query_proto_rawDescGZIP(), []int{8}
}

func (x *QueryResultResponse) GetJob() *QueryJob {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *QueryResultResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *QueryResultResponse) GetJobType() JobType {
	if x != nil {
		return x.JobType
	}
	return JobType_JOB_TYPE_UNSPECIFIED
}

func (x *QueryResultResponse) GetResultMetadata() *QueryResultMetadata {
	if x != nil {
		return x.ResultMetadata
	}
	return nil
}

func (x *QueryResultResponse) GetEngineMetadata() *structpb.Struct {
	if x != nil {
		return x.EngineMetadata
	}
	return nil
}

type SubmitQueryAsyncResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Job              *QueryJob              `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	PullScheduleInMs uint32                 `protobuf:"varint,2,opt,name=pull_schedule_in_ms,json=pullScheduleInMs,proto3" json:"pull_schedule_in_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubmitQueryAsyncResponse) Reset() {
	*x = SubmitQueryAsyncResponse{}
	mi := &file_runner_v1_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitQueryAsyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitQueryAsyncResponse) ProtoMessage() {}

func (x *SubmitQueryAsyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitQueryAsyncResponse.ProtoReflect.Descriptor instead.
func (*SubmitQueryAsyncResponse) Descriptor() ([]byte, []int) {
	return file_runner_v1_query_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitQueryAsyncResponse) GetJob() *QueryJob {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *SubmitQueryAsyncResponse) GetPullScheduleInMs() uint32 {
	if x != nil {
		return x.PullScheduleInMs
	}
	return 0
}

type CheckQueryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobUuid       string                 `protobuf:"bytes,1,opt,name=job_uuid,json=jobUuid,proto3" json:"job_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckQueryStatusRequest) Reset() {
	*x = CheckQueryStatusRequest{}
	mi := &file_runner_v1_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckQueryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckQueryStatusRequest) ProtoMessage() {}

func (x *CheckQueryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckQueryStatusRequest.ProtoReflect.Descriptor instead.
func (*CheckQueryStatusRequest) Descriptor() ([]byte, []int) {
	return file_runner_v1_query_proto_rawDescGZIP(), []int{10}
}

func (x *CheckQueryStatusRequest) GetJobUuid() string {
	if x != nil {
		return x.JobUuid
	}
	return ""
}

type CheckQueryStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *QueryJob              `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckQueryStatusResponse) Reset() {
	*x = CheckQueryStatusResponse{}
	mi := &file_runner_v1_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckQueryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckQueryStatusResponse) ProtoMessage() {}

func (x *CheckQueryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckQueryStatusResponse.ProtoReflect.Descriptor instead.
func (*CheckQueryStatusResponse) Descriptor() ([]byte, []int) {
	return file_runner_v1_query_proto_rawDescGZIP(), []int{11}
}

func (x *CheckQueryStatusResponse) GetJob() *QueryJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type GetQueryResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobUuid       string                 `protobuf:"bytes,1,opt,name=job_uuid,json=jobUuid,proto3" json:"job_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueryResultRequest) Reset() {
	*x = GetQueryResultRequest{}
	mi := &file_runner_v1_query_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueryResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueryResultRequest) ProtoMessage() {}

func (x *GetQueryResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_query_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueryResultRequest.ProtoReflect.Descriptor instead.
func (*GetQueryResultRequest) Descriptor() ([]byte, []int) {
	return file_runner_v1_query_proto_rawDescGZIP(), []int{12}
}

func (x *GetQueryResultRequest) GetJobUuid() string {
	if x != nil {
		return x.JobUuid
	}
	return ""
}

var File_runner_v1_query_proto protoreflect.FileDescriptor

const file_runner_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x15runner/v1/query.proto\x12\trunner.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x19common/v1/operators.proto\"5\n" +
	"\vQueryParams\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"k\n" +
	"\x13QueryResultMetadata\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x12\x1d\n" +
	"\n" +
	"data_types\x18\x02 \x03(\tR\tdataTypes\x12\x1b\n" +
	"\trow_count\x18\x03 \x01(\tR\browCount\"\xb5\x04\n" +
	"\bQueryJob\x12&\n" +
	"\bjob_uuid\x18\x01 \x01(\tB\v\xe0A\x03\xbaH\x05r\x03\xb0\x01\x01R\ajobUuid\x128\n" +
	"\treference\x18\x02 \x01(\tB\x1a\xbaH\x17r\x15\x10\x01\x18\xe8\a2\x0e[a-zA-Z0-9_ ]+R\treference\x126\n" +
	"\x06status\x18\x03 \x01(\x0e2\x14.runner.v1.JobStatusB\b\xbaH\x05\x82\x01\x02\x10\x01R\x06status\x127\n" +
	"\bjob_type\x18\x04 \x01(\x0e2\x12.runner.v1.JobTypeB\b\xbaH\x05\x82\x01\x02\x10\x01R\ajobType\x12 \n" +
	"\x04tags\x18\x05 \x03(\tB\f\xbaH\t\x92\x01\x06\b\x00\x10\n" +
	"\x18\x01R\x04tags\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vadjusted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"adjustedAt:\xbb\x01\xbaH\xb7\x01\x1a\xb4\x01\n" +
	"$query_job.adjusted_at.gte.created_at\x124End date must be greated than or equal to Start Date\x1aVthis.adjusted_at == null || this.adjusted_at == null || this.adjusted_at >= created_at\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x1c\n" +
	"\x1aGetAvailableEnginesRequest\"7\n" +
	"\x1bGetAvailableEnginesResponse\x12\x18\n" +
	"\aengines\x18\x01 \x03(\tR\aengines\"\x97\x02\n" +
	"\x12SubmitQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x16\n" +
	"\x06engine\x18\x02 \x01(\tR\x06engine\x12.\n" +
	"\x06params\x18\x03 \x03(\v2\x16.runner.v1.QueryParamsR\x06params\x12-\n" +
	"\bjob_type\x18\x04 \x01(\x0e2\x12.runner.v1.JobTypeR\ajobType\x129\n" +
	"\boperator\x18\x05 \x01(\x0e2\x1d.common.v1.ComparisonOperatorR\boperator\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8a\x02\n" +
	"\x13QueryResultResponse\x12%\n" +
	"\x03job\x18\x01 \x01(\v2\x13.runner.v1.QueryJobR\x03job\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12-\n" +
	"\bjob_type\x18\x03 \x01(\x0e2\x12.runner.v1.JobTypeR\ajobType\x12G\n" +
	"\x0fresult_metadata\x18\x04 \x01(\v2\x1e.runner.v1.QueryResultMetadataR\x0eresultMetadata\x12@\n" +
	"\x0fengine_metadata\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x0eengineMetadata\"p\n" +
	"\x18SubmitQueryAsyncResponse\x12%\n" +
	"\x03job\x18\x01 \x01(\v2\x13.runner.v1.QueryJobR\x03job\x12-\n" +
	"\x13pull_schedule_in_ms\x18\x02 \x01(\rR\x10pullScheduleInMs\"4\n" +
	"\x17CheckQueryStatusRequest\x12\x19\n" +
	"\bjob_uuid\x18\x01 \x01(\tR\ajobUuid\"A\n" +
	"\x18CheckQueryStatusResponse\x12%\n" +
	"\x03job\x18\x01 \x01(\v2\x13.runner.v1.QueryJobR\x03job\"2\n" +
	"\x15GetQueryResultRequest\x12\x19\n" +
	"\bjob_uuid\x18\x01 \x01(\tR\ajobUuid*\x80\x02\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14JOB_STATUS_SUBMITTED\x10\x01\x12\x15\n" +
	"\x11JOB_STATUS_QUEUED\x10\x02\x12\x1d\n" +
	"\x19JOB_STATUS_WORKER_STARTED\x10\x03\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x04\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x05\x12\x19\n" +
	"\x15JOB_STATUS_SUCCESSFUL\x10\x06\x12\x1e\n" +
	"\x1aJOB_STATUS_RETRIEVING_DATA\x10\a\x12\x1d\n" +
	"\x19JOB_STATUS_WORKER_STOPPED\x10\b*J\n" +
	"\aJobType\x12\x18\n" +
	"\x14JOB_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rJOB_TYPE_SYNC\x10\x01\x12\x12\n" +
	"\x0eJOB_TYPE_ASYNC\x10\x022\xbe\x05\n" +
	"\rRunnerService\x12M\n" +
	"\x04Ping\x12\x16.runner.v1.PingRequest\x1a\x17.runner.v1.PingResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/ping\x12}\n" +
	"\x13GetAvailableEngines\x12%.runner.v1.GetAvailableEnginesRequest\x1a&.runner.v1.GetAvailableEnginesResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/engines\x12i\n" +
	"\vSubmitQuery\x12\x1d.runner.v1.SubmitQueryRequest\x1a\x1e.runner.v1.QueryResultResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/job/sync\x12t\n" +
	"\x10SubmitQueryAsync\x12\x1d.runner.v1.SubmitQueryRequest\x1a#.runner.v1.SubmitQueryAsyncResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/job/async\x12\x82\x01\n" +
	"\x10CheckQueryStatus\x12\".runner.v1.CheckQueryStatusRequest\x1a#.runner.v1.CheckQueryStatusResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/job/{job_uuid}/status\x12y\n" +
	"\x0eGetQueryResult\x12 .runner.v1.GetQueryResultRequest\x1a\x1e.runner.v1.QueryResultResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/job/{job_uuid}/data0\x01B\x97\x01\n" +
	"\rcom.runner.v1B\n" +
	"QueryProtoH\x02P\x01Z3github.com/copito/runner/idl_gen/runner/v1;runnerv1\xa2\x02\x03RXX\xaa\x02\tRunner.V1\xca\x02\tRunner\\V1\xe2\x02\x15Runner\\V1\\GPBMetadata\xea\x02\n" +
	"Runner::V1b\x06proto3"

var (
	file_runner_v1_query_proto_rawDescOnce sync.Once
	file_runner_v1_query_proto_rawDescData []byte
)

func file_runner_v1_query_proto_rawDescGZIP() []byte {
	file_runner_v1_query_proto_rawDescOnce.Do(func() {
		file_runner_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runner_v1_query_proto_rawDesc), len(file_runner_v1_query_proto_rawDesc)))
	})
	return file_runner_v1_query_proto_rawDescData
}

var file_runner_v1_query_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_runner_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_runner_v1_query_proto_goTypes = []any{
	(JobStatus)(0),                      // 0: runner.v1.JobStatus
	(JobType)(0),                        // 1: runner.v1.JobType
	(*QueryParams)(nil),                 // 2: runner.v1.QueryParams
	(*QueryResultMetadata)(nil),         // 3: runner.v1.QueryResultMetadata
	(*QueryJob)(nil),                    // 4: runner.v1.QueryJob
	(*PingRequest)(nil),                 // 5: runner.v1.PingRequest
	(*PingResponse)(nil),                // 6: runner.v1.PingResponse
	(*GetAvailableEnginesRequest)(nil),  // 7: runner.v1.GetAvailableEnginesRequest
	(*GetAvailableEnginesResponse)(nil), // 8: runner.v1.GetAvailableEnginesResponse
	(*SubmitQueryRequest)(nil),          // 9: runner.v1.SubmitQueryRequest
	(*QueryResultResponse)(nil),         // 10: runner.v1.QueryResultResponse
	(*SubmitQueryAsyncResponse)(nil),    // 11: runner.v1.SubmitQueryAsyncResponse
	(*CheckQueryStatusRequest)(nil),     // 12: runner.v1.CheckQueryStatusRequest
	(*CheckQueryStatusResponse)(nil),    // 13: runner.v1.CheckQueryStatusResponse
	(*GetQueryResultRequest)(nil),       // 14: runner.v1.GetQueryResultRequest
	(*timestamppb.Timestamp)(nil),       // 15: google.protobuf.Timestamp
	(v1.ComparisonOperator)(0),          // 16: common.v1.ComparisonOperator
	(*structpb.Struct)(nil),             // 17: google.protobuf.Struct
}
var file_runner_v1_query_proto_depIdxs = []int32{
	0,  // 0: runner.v1.QueryJob.status:type_name -> runner.v1.JobStatus
	1,  // 1: runner.v1.QueryJob.job_type:type_name -> runner.v1.JobType
	15, // 2: runner.v1.QueryJob.created_at:type_name -> google.protobuf.Timestamp
	15, // 3: runner.v1.QueryJob.adjusted_at:type_name -> google.protobuf.Timestamp
	2,  // 4: runner.v1.SubmitQueryRequest.params:type_name -> runner.v1.QueryParams
	1,  // 5: runner.v1.SubmitQueryRequest.job_type:type_name -> runner.v1.JobType
	16, // 6: runner.v1.SubmitQueryRequest.operator:type_name -> common.v1.ComparisonOperator
	15, // 7: runner.v1.SubmitQueryRequest.created_at:type_name -> google.protobuf.Timestamp
	4,  // 8: runner.v1.QueryResultResponse.job:type_name -> runner.v1.QueryJob
	1,  // 9: runner.v1.QueryResultResponse.job_type:type_name -> runner.v1.JobType
	3,  // 10: runner.v1.QueryResultResponse.result_metadata:type_name -> runner.v1.QueryResultMetadata
	17, // 11: runner.v1.QueryResultResponse.engine_metadata:type_name -> google.protobuf.Struct
	4,  // 12: runner.v1.SubmitQueryAsyncResponse.job:type_name -> runner.v1.QueryJob
	4,  // 13: runner.v1.CheckQueryStatusResponse.job:type_name -> runner.v1.QueryJob
	5,  // 14: runner.v1.RunnerService.Ping:input_type -> runner.v1.PingRequest
	7,  // 15: runner.v1.RunnerService.GetAvailableEngines:input_type -> runner.v1.GetAvailableEnginesRequest
	9,  // 16: runner.v1.RunnerService.SubmitQuery:input_type -> runner.v1.SubmitQueryRequest
	9,  // 17: runner.v1.RunnerService.SubmitQueryAsync:input_type -> runner.v1.SubmitQueryRequest
	12, // 18: runner.v1.RunnerService.CheckQueryStatus:input_type -> runner.v1.CheckQueryStatusRequest
	14, // 19: runner.v1.RunnerService.GetQueryResult:input_type -> runner.v1.GetQueryResultRequest
	6,  // 20: runner.v1.RunnerService.Ping:output_type -> runner.v1.PingResponse
	8,  // 21: runner.v1.RunnerService.GetAvailableEngines:output_type -> runner.v1.GetAvailableEnginesResponse
	10, // 22: runner.v1.RunnerService.SubmitQuery:output_type -> runner.v1.QueryResultResponse
	11, // 23: runner.v1.RunnerService.SubmitQueryAsync:output_type -> runner.v1.SubmitQueryAsyncResponse
	13, // 24: runner.v1.RunnerService.CheckQueryStatus:output_type -> runner.v1.CheckQueryStatusResponse
	10, // 25: runner.v1.RunnerService.GetQueryResult:output_type -> runner.v1.QueryResultResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_runner_v1_query_proto_init() }
func file_runner_v1_query_proto_init() {
	if File_runner_v1_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runner_v1_query_proto_rawDesc), len(file_runner_v1_query_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runner_v1_query_proto_goTypes,
		DependencyIndexes: file_runner_v1_query_proto_depIdxs,
		EnumInfos:         file_runner_v1_query_proto_enumTypes,
		MessageInfos:      file_runner_v1_query_proto_msgTypes,
	}.Build()
	File_runner_v1_query_proto = out.File
	file_runner_v1_query_proto_goTypes = nil
	file_runner_v1_query_proto_depIdxs = nil
}
