// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: runner/v1/swagger.proto

package runnerv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_runner_v1_swagger_proto protoreflect.FileDescriptor

const file_runner_v1_swagger_proto_rawDesc = "" +
	"\n" +
	"\x17runner/v1/swagger.proto\x12\trunner.v1\x1a.protoc-gen-openapiv2/options/annotations.protoB\xd2\x02\x92A\xb5\x01\x12S\n" +
	"\n" +
	"Runner API\x12\x0fAPI for example\"/\n" +
	"\aMy team\x12$https://runner-rest.example.com/docs2\x031.0ZL\n" +
	"J\n" +
	"\n" +
	"BearerAuth\x12<\b\x02\x12'Authentication token with Bearer prefix\x1a\rAuthorization \x02b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\n" +
	"\rcom.runner.v1B\fSwaggerProtoH\x02P\x01Z3github.com/copito/runner/idl_gen/runner/v1;runnerv1\xa2\x02\x03RXX\xaa\x02\tRunner.V1\xca\x02\tRunner\\V1\xe2\x02\x15Runner\\V1\\GPBMetadata\xea\x02\n" +
	"Runner::V1b\x06proto3"

var file_runner_v1_swagger_proto_goTypes = []any{}
var file_runner_v1_swagger_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_runner_v1_swagger_proto_init() }
func file_runner_v1_swagger_proto_init() {
	if File_runner_v1_swagger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runner_v1_swagger_proto_rawDesc), len(file_runner_v1_swagger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_runner_v1_swagger_proto_goTypes,
		DependencyIndexes: file_runner_v1_swagger_proto_depIdxs,
	}.Build()
	File_runner_v1_swagger_proto = out.File
	file_runner_v1_swagger_proto_goTypes = nil
	file_runner_v1_swagger_proto_depIdxs = nil
}
